### ISSUE TITLE
Wi-fi and  keyboard layout.

### ISSUE THREAD

**Issue by Gadel13** [wadimw/dell-7577-hackintosh#1]
Wi-Fi on a standard Intel 8265 module, I understand it is impossible to start? Is it possible to buy an external usb wifi module (small in size so as not to stick out of the laptop case)? If you know which module I can buy and do I need to install some kexts?

There is also a question about the keyboard layout. Is it possible to make it work the same way as on Windows or Linux? Because the standard setting for the "shift" button incorrectly defined the layout.

**Comment by wadimw** [comment]
Yes, no Intel wifi card will work on a hackintosh. I used an USB wifi adapter for a while (TP Link TL-WN725N), usually drivers for these are provided by the manufacturer. People tend to advise against these, because depending on their software they may cause issues with sleep and are in general less reliable than dedicated cards but as always YMMV.

As for keyboard I'm not sure what your issue might be, because mine worked fine right away. Are You using latest VoodooPS2 kext? Also, look into Karabiner-Elements, it's a powerful free keyboard remapping software which might have what you need.
