### ISSUE TITLE
White noise from right speaker after wake-up

### ISSUE THREAD

**Issue by bombardinotungtung** [wadimw/dell-7577-hackintosh#4]
First i want to thank to you for your efforts.I have dell 7577 (i7-7700hq 1050ti ALC256) and it works flawlessly everything works except thunderbolt.

But the problem is when i wake up from sleep.i get this very low white noise on right speaker.do you have the same issue ? or do you know what causes it ?

**Comment by wadimw** [comment]
For me there are no such issues. You can try different AppleALC layouts and check if they work for you, I'm currently back on layout 13 (only no headphones there, but I don't have time now to investigate that; when I need them I just reboot with id 21 for a moment).

As for Thunderbolt I didn't check it because I have no external TB devices. USB-C > HDMI dongle works fine though (hotplugging and all). Did you try rebooting with Your device plugged in? I've read somewhere that only hotplugging doesn't work for hacks.

**Comment by baritonerosecandytea** [comment]
i dont use thunderbolt either.just wanted to say everthing works.

for audio issue i some told that i must install codeccommander.kext.also it happens only after sleep.so i probably not gonna change the layout and risk headphone jack.thanks
