### ISSUE TITLE
Will this work with Dell 7567

### ISSUE THREAD

**Issue by kodidono** [wadimw/dell-7577-hackintosh#5]
Will this work with Dell 7567 ?
i7-7700hq
what needs to be replaced?
what would you recommend ?
thank you :)

**Comment by wadimw** [comment]
Well I based my hack quite heavily on this repo https://github.com/Nihhaar/Hackintosh-Dell-7567 so You may wish to look around in there. Also when generating Your SMBIOS I suggest You choose MacBookPro14,3 instead of 14,1. Other than that, I think there is a strong chance it will work for You right away.

**Comment by kodidono** [comment]
after loading the clover I get a dark screen..
this is probably a problem with the graphics card

**Comment by alifurkanbudak** [comment]
@kodidono Did you find a solution for this issue?
