### ISSUE TITLE
Question: Could you specify the kext file for the USB C

### ISSUE THREAD

**Issue by mohammedhemaid** [wadimw/dell-7577-hackintosh#6]
Hello, 
I have tried  USB-Map-Dell7577.kext but the USB didn't work 100%, I used it to connect my mobile it just charging but I can't use it for debugging.

**Comment by wadimw** [comment]
Did it work for you on some older EFI? If so, please let me know so that I can investigate.

From what I've found so far (you can read it in journal) USBC ports here are managed by Thunderbolt controller (Alpine Ridge) which is being turned off on launch if there are no devices present. Windows has a way to turn it on later, but apparently it may be wonky on hackintoshes - I didn't test it yet.

All in all, it should work if you plug the device in before turning laptop on (or reboot after plugging in). Alternatively, you could look into https://dortania.github.io/OpenCore-Post-Install/universal/sleep.html#fixing-thunderbolt and let me know if you manage to get it working.

**Comment by mohammedhemaid** [comment]
Thank you for your reply.

I used USB-Map-Dell7577.kext. I didn't know I should plug in the device before the boot, now it works.

Thank you very much!
